/********************************************************************************
** Form generated from reading UI file 'tabsTest.ui'
**
** Created by: Qt User Interface Compiler version 6.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TABSTEST_H
#define UI_TABSTEST_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_tabsTest
{
public:
    QWidget *centralwidget;
    QPushButton *btnReset;
    QPushButton *btnView;
    QPushButton *btnExit;
    QPushButton *btnUpdate;
    QTabWidget *tabWidget;
    QWidget *tabActivity;
    QLabel *lblActivityDate;
    QLineEdit *txtActivityDistance;
    QLineEdit *txtActivityDuration;
    QComboBox *cboActivityActivity;
    QLabel *lblActivityActivity;
    QLabel *lblActivityDuration;
    QLabel *lblActivityComment;
    QLineEdit *txtActivityComment;
    QLabel *lblActivityDistance;
    QLabel *lblActivityHeartRate;
    QLabel *lblActivityMaxHeartRate;
    QLineEdit *txtActivityHeartRate;
    QLineEdit *txtActivityMaxHeartRate;
    QComboBox *cboActivityModel;
    QComboBox *cboActivityComments;
    QDateEdit *activityDateEdit;
    QPushButton *btnActivityLaps;
    QLineEdit *txtActivityLaps;
    QPushButton *btnActivityCalculate;
    QLabel *lblActivityDistance2;
    QLineEdit *txtActivityDistance2;
    QWidget *tabAppointments;
    QLabel *lblAppointmentsDate;
    QLabel *lblAppointmentsType;
    QLabel *lblAppointmentsName;
    QLineEdit *txtAppointmentsName;
    QLineEdit *txtAppointmentsType;
    QLabel *lblAppointmentsComment;
    QLineEdit *txtAppointmentsComment;
    QDateEdit *appointmentsDateEdit;
    QWidget *tabExercise;
    QLabel *lblExerciseDate;
    QLabel *lblExerciseExercise;
    QComboBox *cboExerciseExercise;
    QLineEdit *txtExerciseDuration;
    QLabel *lblExerciseDuration;
    QLabel *lblExerciseComment;
    QLineEdit *txtExerciseComment;
    QLabel *lblExerciseReps;
    QLineEdit *txtExerciseReps;
    QLabel *lblExerciseHeartRate;
    QLabel *lblExerciseMaxHeartRate;
    QLineEdit *txtExerciseHeartRate;
    QLineEdit *txtExerciseMaxHeartRate;
    QDateEdit *exerciseDateEdit;
    QLabel *lblExerciseSets;
    QLineEdit *txtExerciseSets;
    QLabel *lblExerciseWeight;
    QLineEdit *txtExerciseWeight;
    QWidget *tabIllness;
    QLabel *lblIllnessName;
    QLineEdit *txtIllnessName;
    QLabel *lblIllnessComment;
    QLineEdit *txtIllnessComment;
    QLabel *lblIllnessDate;
    QDateEdit *illnessDateEdit;
    QWidget *tabInjury;
    QLabel *lblInjuryDate;
    QLabel *lblInjuryName;
    QLineEdit *txtInjuryName;
    QLabel *lblInjuryComment;
    QLineEdit *txtInjuryComment;
    QDateEdit *injuryDateEdit;
    QWidget *tabMouthProblems;
    QLabel *lblMouthDate;
    QLabel *lblMouthTime;
    QLineEdit *txtMouthTime;
    QLabel *lblMouthTypeOfProblem;
    QLineEdit *txtMouthTypeOfProblem;
    QLabel *lblMouthTooth1;
    QLineEdit *txtMouthTooth1;
    QLabel *lblMouthTooth2;
    QLineEdit *txtMouthTooth2;
    QLabel *lblMouthComment;
    QLineEdit *txtMouthComment;
    QDateEdit *mouthDateEdit;
    QWidget *tabMedicine;
    QLabel *lblMedicinesEndDate;
    QComboBox *cboMedicinesMedicine;
    QLabel *lblMedicinesMedicine;
    QComboBox *cboMedicinesUnit;
    QLineEdit *txtMedicinesDosage;
    QLineEdit *txtMedicinesTimesTaken;
    QLabel *lblMedicinesTimesTaken;
    QLabel *lblMediconesComment;
    QLineEdit *txtMedicinesComment;
    QLabel *lblMedicinesStartDate;
    QDateEdit *medicineStartDateEdit;
    QDateEdit *medicineEndDateEdit;
    QWidget *tabPathology;
    QLabel *lblPathologyDate;
    QLabel *lblPathologyCholesterol;
    QLineEdit *txtPathologyCholesterol;
    QLabel *lblPathologyHDL;
    QLineEdit *txtPathologyHDL;
    QLabel *lblPathologyTriglycerides;
    QLineEdit *txtPathologyTriglycerides;
    QLabel *lblPathologyGlucose;
    QLineEdit *txtPathologyGlucose;
    QDateEdit *pathologyDateEdit;
    QLabel *lblPathologyHbA1c;
    QLineEdit *txtPathologyHbA1c;
    QLabel *lblPathologyOneHour;
    QLineEdit *txtPathologyOneHour;
    QLabel *lblPathologyTwoHour;
    QLineEdit *txtPathologyTwoHour;
    QWidget *tabWeights;
    QLabel *lblWeightsTime;
    QComboBox *cboWeightsTime;
    QLabel *lblWeightsWeight;
    QLineEdit *txtWeightsWeight;
    QLabel *lblWeightsDate;
    QLabel *lblWeightsComment;
    QLineEdit *txtWeightsComment;
    QDateEdit *weightsDateEdit;
    QPushButton *btnWeightsTomorrow;
    QWidget *tabEyes;
    QLabel *lblEyesDate;
    QLabel *lblEyesReason;
    QLineEdit *txtEyesReason;
    QLabel *lblEyesComment;
    QLineEdit *txtEyesComment;
    QDateEdit *eyesDateEdit;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *tabsTest)
    {
        if (tabsTest->objectName().isEmpty())
            tabsTest->setObjectName("tabsTest");
        tabsTest->resize(787, 474);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(175, 179, 195, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(215, 217, 225, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(87, 89, 97, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(117, 119, 130, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush7(QColor(0, 0, 0, 128));
        brush7.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush7);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        QBrush brush8(QColor(0, 0, 0, 128));
        brush8.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
#endif
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        tabsTest->setPalette(palette);
        QFont font;
        tabsTest->setFont(font);
        centralwidget = new QWidget(tabsTest);
        centralwidget->setObjectName("centralwidget");
        QPalette palette1;
        centralwidget->setPalette(palette1);
        btnReset = new QPushButton(centralwidget);
        btnReset->setObjectName("btnReset");
        btnReset->setGeometry(QRect(274, 400, 91, 28));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush10(QColor(189, 168, 195, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush11(QColor(222, 211, 225, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        QBrush brush12(QColor(94, 84, 97, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(126, 112, 130, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush11);
        QBrush brush14(QColor(0, 0, 0, 128));
        brush14.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush14);
#endif
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush11);
        QBrush brush15(QColor(0, 0, 0, 128));
        brush15.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush15);
#endif
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        QBrush brush16(QColor(0, 0, 0, 128));
        brush16.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush16);
#endif
        btnReset->setPalette(palette2);
        QFont font1;
        font1.setPointSize(14);
        btnReset->setFont(font1);
        btnView = new QPushButton(centralwidget);
        btnView->setObjectName("btnView");
        btnView->setGeometry(QRect(80, 400, 91, 28));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush17(QColor(138, 195, 147, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush17);
        QBrush brush18(QColor(218, 255, 224, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush18);
        QBrush brush19(QColor(178, 225, 185, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush19);
        QBrush brush20(QColor(69, 97, 73, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush20);
        QBrush brush21(QColor(92, 130, 98, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush21);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush22(QColor(196, 225, 201, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush22);
        QBrush brush23(QColor(0, 0, 0, 128));
        brush23.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette::Active, QPalette::PlaceholderText, brush23);
#endif
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush18);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush19);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush20);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush21);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush22);
        QBrush brush24(QColor(0, 0, 0, 128));
        brush24.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush24);
#endif
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush18);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush19);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush21);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        QBrush brush25(QColor(0, 0, 0, 128));
        brush25.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush25);
#endif
        btnView->setPalette(palette3);
        btnView->setFont(font1);
        btnExit = new QPushButton(centralwidget);
        btnExit->setObjectName("btnExit");
        btnExit->setGeometry(QRect(640, 390, 91, 51));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush26(QColor(252, 55, 127, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush26);
        QBrush brush27(QColor(255, 179, 207, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush27);
        QBrush brush28(QColor(253, 117, 167, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush28);
        QBrush brush29(QColor(126, 27, 63, 255));
        brush29.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush29);
        QBrush brush30(QColor(168, 36, 85, 255));
        brush30.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush30);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush26);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush31(QColor(253, 155, 191, 255));
        brush31.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush31);
        QBrush brush32(QColor(0, 0, 0, 128));
        brush32.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush32);
#endif
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush26);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush27);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush28);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush29);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush30);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush26);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush31);
        QBrush brush33(QColor(0, 0, 0, 128));
        brush33.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush33);
#endif
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush26);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush27);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush28);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush30);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush26);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush26);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush26);
        QBrush brush34(QColor(0, 0, 0, 128));
        brush34.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush34);
#endif
        btnExit->setPalette(palette4);
        QFont font2;
        font2.setPointSize(13);
        font2.setBold(true);
        btnExit->setFont(font2);
        btnUpdate = new QPushButton(centralwidget);
        btnUpdate->setObjectName("btnUpdate");
        btnUpdate->setGeometry(QRect(450, 400, 91, 28));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush35(QColor(255, 207, 85, 255));
        brush35.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush35);
        QBrush brush36(QColor(255, 243, 213, 255));
        brush36.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush36);
        QBrush brush37(QColor(255, 225, 149, 255));
        brush37.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush37);
        QBrush brush38(QColor(127, 103, 42, 255));
        brush38.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush38);
        QBrush brush39(QColor(170, 138, 56, 255));
        brush39.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush39);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush35);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush40(QColor(255, 231, 170, 255));
        brush40.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush40);
        QBrush brush41(QColor(0, 0, 0, 128));
        brush41.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush41);
#endif
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush35);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush36);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush37);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush38);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush39);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush35);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush40);
        QBrush brush42(QColor(0, 0, 0, 128));
        brush42.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush42);
#endif
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush38);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush36);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush37);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush38);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush39);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush38);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush38);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush35);
        QBrush brush43(QColor(0, 0, 0, 128));
        brush43.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush43);
#endif
        btnUpdate->setPalette(palette5);
        btnUpdate->setFont(font1);
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName("tabWidget");
        tabWidget->setGeometry(QRect(15, 20, 751, 361));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(tabWidget->sizePolicy().hasHeightForWidth());
        tabWidget->setSizePolicy(sizePolicy);
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush44(QColor(188, 172, 195, 255));
        brush44.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush44);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush45(QColor(221, 213, 225, 255));
        brush45.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush45);
        QBrush brush46(QColor(94, 86, 97, 255));
        brush46.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush46);
        QBrush brush47(QColor(125, 115, 130, 255));
        brush47.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush47);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush44);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush45);
        QBrush brush48(QColor(0, 0, 0, 128));
        brush48.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette::Active, QPalette::PlaceholderText, brush48);
#endif
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush44);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush45);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush46);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush47);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush44);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush45);
        QBrush brush49(QColor(0, 0, 0, 128));
        brush49.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush49);
#endif
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush44);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush45);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush47);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush44);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush44);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush44);
        QBrush brush50(QColor(0, 0, 0, 128));
        brush50.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush50);
#endif
        tabWidget->setPalette(palette6);
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(true);
        tabWidget->setFont(font3);
        tabWidget->setTabShape(QTabWidget::Rounded);
        tabActivity = new QWidget();
        tabActivity->setObjectName("tabActivity");
        lblActivityDate = new QLabel(tabActivity);
        lblActivityDate->setObjectName("lblActivityDate");
        lblActivityDate->setGeometry(QRect(20, 20, 61, 23));
        QFont font4;
        font4.setPointSize(14);
        font4.setBold(true);
        lblActivityDate->setFont(font4);
        txtActivityDistance = new QLineEdit(tabActivity);
        txtActivityDistance->setObjectName("txtActivityDistance");
        txtActivityDistance->setGeometry(QRect(210, 100, 51, 29));
        QFont font5;
        font5.setPointSize(12);
        font5.setBold(true);
        txtActivityDistance->setFont(font5);
        txtActivityDuration = new QLineEdit(tabActivity);
        txtActivityDuration->setObjectName("txtActivityDuration");
        txtActivityDuration->setGeometry(QRect(210, 140, 101, 29));
        txtActivityDuration->setFont(font5);
        txtActivityDuration->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cboActivityActivity = new QComboBox(tabActivity);
        cboActivityActivity->setObjectName("cboActivityActivity");
        cboActivityActivity->setGeometry(QRect(210, 60, 101, 27));
        cboActivityActivity->setFont(font5);
        lblActivityActivity = new QLabel(tabActivity);
        lblActivityActivity->setObjectName("lblActivityActivity");
        lblActivityActivity->setGeometry(QRect(20, 60, 91, 23));
        lblActivityActivity->setFont(font4);
        lblActivityDuration = new QLabel(tabActivity);
        lblActivityDuration->setObjectName("lblActivityDuration");
        lblActivityDuration->setGeometry(QRect(20, 140, 181, 24));
        lblActivityDuration->setFont(font4);
        lblActivityComment = new QLabel(tabActivity);
        lblActivityComment->setObjectName("lblActivityComment");
        lblActivityComment->setGeometry(QRect(20, 220, 91, 23));
        lblActivityComment->setFont(font4);
        txtActivityComment = new QLineEdit(tabActivity);
        txtActivityComment->setObjectName("txtActivityComment");
        txtActivityComment->setGeometry(QRect(210, 220, 261, 27));
        txtActivityComment->setFont(font5);
        lblActivityDistance = new QLabel(tabActivity);
        lblActivityDistance->setObjectName("lblActivityDistance");
        lblActivityDistance->setGeometry(QRect(20, 100, 141, 24));
        lblActivityDistance->setFont(font4);
        lblActivityDistance->setAutoFillBackground(true);
        lblActivityHeartRate = new QLabel(tabActivity);
        lblActivityHeartRate->setObjectName("lblActivityHeartRate");
        lblActivityHeartRate->setGeometry(QRect(20, 180, 121, 24));
        lblActivityHeartRate->setFont(font4);
        lblActivityMaxHeartRate = new QLabel(tabActivity);
        lblActivityMaxHeartRate->setObjectName("lblActivityMaxHeartRate");
        lblActivityMaxHeartRate->setGeometry(QRect(320, 180, 161, 24));
        lblActivityMaxHeartRate->setFont(font4);
        txtActivityHeartRate = new QLineEdit(tabActivity);
        txtActivityHeartRate->setObjectName("txtActivityHeartRate");
        txtActivityHeartRate->setGeometry(QRect(210, 180, 41, 27));
        txtActivityHeartRate->setFont(font5);
        txtActivityMaxHeartRate = new QLineEdit(tabActivity);
        txtActivityMaxHeartRate->setObjectName("txtActivityMaxHeartRate");
        txtActivityMaxHeartRate->setGeometry(QRect(500, 180, 41, 27));
        txtActivityMaxHeartRate->setFont(font5);
        cboActivityModel = new QComboBox(tabActivity);
        cboActivityModel->setObjectName("cboActivityModel");
        cboActivityModel->setGeometry(QRect(330, 60, 151, 27));
        cboActivityModel->setFont(font5);
        cboActivityComments = new QComboBox(tabActivity);
        cboActivityComments->setObjectName("cboActivityComments");
        cboActivityComments->setGeometry(QRect(490, 220, 221, 27));
        cboActivityComments->setFont(font3);
        activityDateEdit = new QDateEdit(tabActivity);
        activityDateEdit->setObjectName("activityDateEdit");
        activityDateEdit->setGeometry(QRect(210, 20, 151, 27));
        activityDateEdit->setFont(font3);
        activityDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        activityDateEdit->setCalendarPopup(true);
        btnActivityLaps = new QPushButton(tabActivity);
        btnActivityLaps->setObjectName("btnActivityLaps");
        btnActivityLaps->setGeometry(QRect(570, 60, 91, 28));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush51(QColor(85, 195, 77, 255));
        brush51.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush51);
        QBrush brush52(QColor(146, 255, 138, 255));
        brush52.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush52);
        QBrush brush53(QColor(115, 225, 107, 255));
        brush53.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush53);
        QBrush brush54(QColor(42, 97, 38, 255));
        brush54.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush54);
        QBrush brush55(QColor(56, 130, 51, 255));
        brush55.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush55);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush51);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush56(QColor(170, 225, 166, 255));
        brush56.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush56);
        QBrush brush57(QColor(0, 0, 0, 128));
        brush57.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush57);
#endif
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush51);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush52);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush53);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush54);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush55);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush51);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush56);
        QBrush brush58(QColor(0, 0, 0, 128));
        brush58.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush58);
#endif
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush54);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush51);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush52);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush53);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush54);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush55);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush54);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush54);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush51);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush51);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush51);
        QBrush brush59(QColor(0, 0, 0, 128));
        brush59.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush59);
#endif
        btnActivityLaps->setPalette(palette7);
        btnActivityLaps->setFont(font5);
        txtActivityLaps = new QLineEdit(tabActivity);
        txtActivityLaps->setObjectName("txtActivityLaps");
        txtActivityLaps->setGeometry(QRect(500, 60, 51, 28));
        txtActivityLaps->setFont(font5);
        btnActivityCalculate = new QPushButton(tabActivity);
        btnActivityCalculate->setObjectName("btnActivityCalculate");
        btnActivityCalculate->setGeometry(QRect(520, 130, 91, 27));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush51);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush52);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush53);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush54);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush55);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush51);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush56);
        QBrush brush60(QColor(0, 0, 0, 128));
        brush60.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette::Active, QPalette::PlaceholderText, brush60);
#endif
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush51);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush52);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush53);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush54);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush55);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush51);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush56);
        QBrush brush61(QColor(0, 0, 0, 128));
        brush61.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush61);
#endif
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush54);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush51);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush52);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush53);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush54);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush55);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush54);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush54);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush51);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush51);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush51);
        QBrush brush62(QColor(0, 0, 0, 128));
        brush62.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush62);
#endif
        btnActivityCalculate->setPalette(palette8);
        btnActivityCalculate->setFont(font5);
        lblActivityDistance2 = new QLabel(tabActivity);
        lblActivityDistance2->setObjectName("lblActivityDistance2");
        lblActivityDistance2->setGeometry(QRect(440, 100, 161, 24));
        lblActivityDistance2->setFont(font4);
        lblActivityDistance2->setAutoFillBackground(true);
        txtActivityDistance2 = new QLineEdit(tabActivity);
        txtActivityDistance2->setObjectName("txtActivityDistance2");
        txtActivityDistance2->setGeometry(QRect(610, 100, 51, 27));
        txtActivityDistance2->setFont(font5);
        tabWidget->addTab(tabActivity, QString());
        tabAppointments = new QWidget();
        tabAppointments->setObjectName("tabAppointments");
        lblAppointmentsDate = new QLabel(tabAppointments);
        lblAppointmentsDate->setObjectName("lblAppointmentsDate");
        lblAppointmentsDate->setGeometry(QRect(20, 20, 61, 23));
        lblAppointmentsDate->setFont(font4);
        lblAppointmentsType = new QLabel(tabAppointments);
        lblAppointmentsType->setObjectName("lblAppointmentsType");
        lblAppointmentsType->setGeometry(QRect(20, 70, 61, 23));
        lblAppointmentsType->setFont(font4);
        lblAppointmentsName = new QLabel(tabAppointments);
        lblAppointmentsName->setObjectName("lblAppointmentsName");
        lblAppointmentsName->setGeometry(QRect(20, 120, 61, 23));
        lblAppointmentsName->setFont(font4);
        txtAppointmentsName = new QLineEdit(tabAppointments);
        txtAppointmentsName->setObjectName("txtAppointmentsName");
        txtAppointmentsName->setGeometry(QRect(210, 120, 113, 27));
        txtAppointmentsName->setFont(font5);
        txtAppointmentsType = new QLineEdit(tabAppointments);
        txtAppointmentsType->setObjectName("txtAppointmentsType");
        txtAppointmentsType->setGeometry(QRect(210, 70, 101, 27));
        txtAppointmentsType->setFont(font5);
        lblAppointmentsComment = new QLabel(tabAppointments);
        lblAppointmentsComment->setObjectName("lblAppointmentsComment");
        lblAppointmentsComment->setGeometry(QRect(20, 170, 101, 23));
        lblAppointmentsComment->setFont(font4);
        txtAppointmentsComment = new QLineEdit(tabAppointments);
        txtAppointmentsComment->setObjectName("txtAppointmentsComment");
        txtAppointmentsComment->setGeometry(QRect(210, 170, 471, 27));
        txtAppointmentsComment->setFont(font5);
        appointmentsDateEdit = new QDateEdit(tabAppointments);
        appointmentsDateEdit->setObjectName("appointmentsDateEdit");
        appointmentsDateEdit->setGeometry(QRect(210, 20, 151, 27));
        appointmentsDateEdit->setFont(font3);
        appointmentsDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        appointmentsDateEdit->setCalendarPopup(true);
        tabWidget->addTab(tabAppointments, QString());
        tabExercise = new QWidget();
        tabExercise->setObjectName("tabExercise");
        lblExerciseDate = new QLabel(tabExercise);
        lblExerciseDate->setObjectName("lblExerciseDate");
        lblExerciseDate->setGeometry(QRect(20, 20, 61, 23));
        lblExerciseDate->setFont(font4);
        lblExerciseExercise = new QLabel(tabExercise);
        lblExerciseExercise->setObjectName("lblExerciseExercise");
        lblExerciseExercise->setGeometry(QRect(20, 60, 91, 24));
        lblExerciseExercise->setFont(font4);
        cboExerciseExercise = new QComboBox(tabExercise);
        cboExerciseExercise->setObjectName("cboExerciseExercise");
        cboExerciseExercise->setGeometry(QRect(210, 60, 171, 27));
        cboExerciseExercise->setFont(font4);
        txtExerciseDuration = new QLineEdit(tabExercise);
        txtExerciseDuration->setObjectName("txtExerciseDuration");
        txtExerciseDuration->setGeometry(QRect(210, 140, 61, 27));
        txtExerciseDuration->setFont(font5);
        txtExerciseDuration->setFocusPolicy(Qt::WheelFocus);
        lblExerciseDuration = new QLabel(tabExercise);
        lblExerciseDuration->setObjectName("lblExerciseDuration");
        lblExerciseDuration->setGeometry(QRect(20, 140, 161, 24));
        lblExerciseDuration->setFont(font4);
        lblExerciseComment = new QLabel(tabExercise);
        lblExerciseComment->setObjectName("lblExerciseComment");
        lblExerciseComment->setGeometry(QRect(20, 220, 101, 23));
        lblExerciseComment->setFont(font4);
        txtExerciseComment = new QLineEdit(tabExercise);
        txtExerciseComment->setObjectName("txtExerciseComment");
        txtExerciseComment->setGeometry(QRect(210, 220, 481, 27));
        txtExerciseComment->setFont(font5);
        lblExerciseReps = new QLabel(tabExercise);
        lblExerciseReps->setObjectName("lblExerciseReps");
        lblExerciseReps->setGeometry(QRect(320, 100, 61, 27));
        lblExerciseReps->setFont(font4);
        txtExerciseReps = new QLineEdit(tabExercise);
        txtExerciseReps->setObjectName("txtExerciseReps");
        txtExerciseReps->setGeometry(QRect(420, 100, 51, 27));
        txtExerciseReps->setFont(font5);
        lblExerciseHeartRate = new QLabel(tabExercise);
        lblExerciseHeartRate->setObjectName("lblExerciseHeartRate");
        lblExerciseHeartRate->setGeometry(QRect(20, 180, 111, 23));
        lblExerciseHeartRate->setFont(font4);
        lblExerciseMaxHeartRate = new QLabel(tabExercise);
        lblExerciseMaxHeartRate->setObjectName("lblExerciseMaxHeartRate");
        lblExerciseMaxHeartRate->setGeometry(QRect(320, 180, 151, 23));
        lblExerciseMaxHeartRate->setFont(font4);
        txtExerciseHeartRate = new QLineEdit(tabExercise);
        txtExerciseHeartRate->setObjectName("txtExerciseHeartRate");
        txtExerciseHeartRate->setGeometry(QRect(210, 180, 41, 27));
        txtExerciseHeartRate->setFont(font5);
        txtExerciseMaxHeartRate = new QLineEdit(tabExercise);
        txtExerciseMaxHeartRate->setObjectName("txtExerciseMaxHeartRate");
        txtExerciseMaxHeartRate->setGeometry(QRect(490, 180, 41, 27));
        txtExerciseMaxHeartRate->setFont(font5);
        exerciseDateEdit = new QDateEdit(tabExercise);
        exerciseDateEdit->setObjectName("exerciseDateEdit");
        exerciseDateEdit->setGeometry(QRect(210, 20, 151, 27));
        exerciseDateEdit->setFont(font3);
        exerciseDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        exerciseDateEdit->setCalendarPopup(true);
        lblExerciseSets = new QLabel(tabExercise);
        lblExerciseSets->setObjectName("lblExerciseSets");
        lblExerciseSets->setGeometry(QRect(20, 100, 61, 27));
        lblExerciseSets->setFont(font4);
        lblExerciseSets->setContextMenuPolicy(Qt::NoContextMenu);
        txtExerciseSets = new QLineEdit(tabExercise);
        txtExerciseSets->setObjectName("txtExerciseSets");
        txtExerciseSets->setGeometry(QRect(210, 100, 51, 27));
        txtExerciseSets->setFont(font5);
        lblExerciseWeight = new QLabel(tabExercise);
        lblExerciseWeight->setObjectName("lblExerciseWeight");
        lblExerciseWeight->setGeometry(QRect(540, 100, 71, 27));
        lblExerciseWeight->setFont(font4);
        txtExerciseWeight = new QLineEdit(tabExercise);
        txtExerciseWeight->setObjectName("txtExerciseWeight");
        txtExerciseWeight->setGeometry(QRect(640, 100, 51, 27));
        txtExerciseWeight->setFont(font5);
        tabWidget->addTab(tabExercise, QString());
        tabIllness = new QWidget();
        tabIllness->setObjectName("tabIllness");
        lblIllnessName = new QLabel(tabIllness);
        lblIllnessName->setObjectName("lblIllnessName");
        lblIllnessName->setGeometry(QRect(20, 70, 61, 23));
        lblIllnessName->setFont(font4);
        txtIllnessName = new QLineEdit(tabIllness);
        txtIllnessName->setObjectName("txtIllnessName");
        txtIllnessName->setGeometry(QRect(210, 70, 131, 27));
        txtIllnessName->setFont(font5);
        lblIllnessComment = new QLabel(tabIllness);
        lblIllnessComment->setObjectName("lblIllnessComment");
        lblIllnessComment->setGeometry(QRect(20, 110, 91, 24));
        lblIllnessComment->setFont(font4);
        txtIllnessComment = new QLineEdit(tabIllness);
        txtIllnessComment->setObjectName("txtIllnessComment");
        txtIllnessComment->setGeometry(QRect(210, 110, 401, 27));
        txtIllnessComment->setFont(font5);
        lblIllnessDate = new QLabel(tabIllness);
        lblIllnessDate->setObjectName("lblIllnessDate");
        lblIllnessDate->setGeometry(QRect(20, 20, 61, 23));
        lblIllnessDate->setFont(font4);
        illnessDateEdit = new QDateEdit(tabIllness);
        illnessDateEdit->setObjectName("illnessDateEdit");
        illnessDateEdit->setGeometry(QRect(210, 20, 151, 27));
        illnessDateEdit->setFont(font3);
        illnessDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        illnessDateEdit->setCalendarPopup(true);
        tabWidget->addTab(tabIllness, QString());
        tabInjury = new QWidget();
        tabInjury->setObjectName("tabInjury");
        lblInjuryDate = new QLabel(tabInjury);
        lblInjuryDate->setObjectName("lblInjuryDate");
        lblInjuryDate->setGeometry(QRect(20, 20, 61, 23));
        lblInjuryDate->setFont(font4);
        lblInjuryName = new QLabel(tabInjury);
        lblInjuryName->setObjectName("lblInjuryName");
        lblInjuryName->setGeometry(QRect(20, 70, 61, 23));
        lblInjuryName->setFont(font4);
        txtInjuryName = new QLineEdit(tabInjury);
        txtInjuryName->setObjectName("txtInjuryName");
        txtInjuryName->setGeometry(QRect(210, 70, 151, 27));
        txtInjuryName->setFont(font5);
        lblInjuryComment = new QLabel(tabInjury);
        lblInjuryComment->setObjectName("lblInjuryComment");
        lblInjuryComment->setGeometry(QRect(20, 110, 91, 24));
        lblInjuryComment->setFont(font4);
        txtInjuryComment = new QLineEdit(tabInjury);
        txtInjuryComment->setObjectName("txtInjuryComment");
        txtInjuryComment->setGeometry(QRect(210, 110, 391, 27));
        txtInjuryComment->setFont(font5);
        injuryDateEdit = new QDateEdit(tabInjury);
        injuryDateEdit->setObjectName("injuryDateEdit");
        injuryDateEdit->setGeometry(QRect(210, 20, 151, 27));
        injuryDateEdit->setFont(font3);
        injuryDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        injuryDateEdit->setCalendarPopup(true);
        tabWidget->addTab(tabInjury, QString());
        tabMouthProblems = new QWidget();
        tabMouthProblems->setObjectName("tabMouthProblems");
        lblMouthDate = new QLabel(tabMouthProblems);
        lblMouthDate->setObjectName("lblMouthDate");
        lblMouthDate->setGeometry(QRect(20, 20, 61, 23));
        lblMouthDate->setFont(font4);
        lblMouthTime = new QLabel(tabMouthProblems);
        lblMouthTime->setObjectName("lblMouthTime");
        lblMouthTime->setGeometry(QRect(20, 70, 61, 23));
        lblMouthTime->setFont(font4);
        txtMouthTime = new QLineEdit(tabMouthProblems);
        txtMouthTime->setObjectName("txtMouthTime");
        txtMouthTime->setGeometry(QRect(210, 70, 61, 27));
        txtMouthTime->setFont(font5);
        lblMouthTypeOfProblem = new QLabel(tabMouthProblems);
        lblMouthTypeOfProblem->setObjectName("lblMouthTypeOfProblem");
        lblMouthTypeOfProblem->setGeometry(QRect(20, 120, 61, 23));
        lblMouthTypeOfProblem->setFont(font4);
        txtMouthTypeOfProblem = new QLineEdit(tabMouthProblems);
        txtMouthTypeOfProblem->setObjectName("txtMouthTypeOfProblem");
        txtMouthTypeOfProblem->setGeometry(QRect(210, 120, 161, 27));
        txtMouthTypeOfProblem->setFont(font5);
        lblMouthTooth1 = new QLabel(tabMouthProblems);
        lblMouthTooth1->setObjectName("lblMouthTooth1");
        lblMouthTooth1->setGeometry(QRect(20, 170, 71, 23));
        lblMouthTooth1->setFont(font4);
        txtMouthTooth1 = new QLineEdit(tabMouthProblems);
        txtMouthTooth1->setObjectName("txtMouthTooth1");
        txtMouthTooth1->setGeometry(QRect(210, 170, 101, 27));
        txtMouthTooth1->setFont(font5);
        lblMouthTooth2 = new QLabel(tabMouthProblems);
        lblMouthTooth2->setObjectName("lblMouthTooth2");
        lblMouthTooth2->setGeometry(QRect(380, 170, 71, 23));
        lblMouthTooth2->setFont(font4);
        txtMouthTooth2 = new QLineEdit(tabMouthProblems);
        txtMouthTooth2->setObjectName("txtMouthTooth2");
        txtMouthTooth2->setGeometry(QRect(490, 170, 101, 27));
        txtMouthTooth2->setFont(font5);
        lblMouthComment = new QLabel(tabMouthProblems);
        lblMouthComment->setObjectName("lblMouthComment");
        lblMouthComment->setGeometry(QRect(20, 220, 101, 23));
        lblMouthComment->setFont(font4);
        txtMouthComment = new QLineEdit(tabMouthProblems);
        txtMouthComment->setObjectName("txtMouthComment");
        txtMouthComment->setGeometry(QRect(210, 220, 381, 27));
        txtMouthComment->setFont(font5);
        mouthDateEdit = new QDateEdit(tabMouthProblems);
        mouthDateEdit->setObjectName("mouthDateEdit");
        mouthDateEdit->setGeometry(QRect(210, 20, 151, 27));
        mouthDateEdit->setFont(font3);
        mouthDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        mouthDateEdit->setCalendarPopup(true);
        tabWidget->addTab(tabMouthProblems, QString());
        tabMedicine = new QWidget();
        tabMedicine->setObjectName("tabMedicine");
        lblMedicinesEndDate = new QLabel(tabMedicine);
        lblMedicinesEndDate->setObjectName("lblMedicinesEndDate");
        lblMedicinesEndDate->setGeometry(QRect(20, 60, 91, 24));
        lblMedicinesEndDate->setFont(font4);
        cboMedicinesMedicine = new QComboBox(tabMedicine);
        cboMedicinesMedicine->setObjectName("cboMedicinesMedicine");
        cboMedicinesMedicine->setGeometry(QRect(190, 100, 131, 27));
        cboMedicinesMedicine->setFont(font4);
        lblMedicinesMedicine = new QLabel(tabMedicine);
        lblMedicinesMedicine->setObjectName("lblMedicinesMedicine");
        lblMedicinesMedicine->setGeometry(QRect(20, 100, 91, 24));
        lblMedicinesMedicine->setFont(font4);
        cboMedicinesUnit = new QComboBox(tabMedicine);
        cboMedicinesUnit->setObjectName("cboMedicinesUnit");
        cboMedicinesUnit->setGeometry(QRect(490, 100, 111, 27));
        cboMedicinesUnit->setFont(font4);
        txtMedicinesDosage = new QLineEdit(tabMedicine);
        txtMedicinesDosage->setObjectName("txtMedicinesDosage");
        txtMedicinesDosage->setGeometry(QRect(360, 100, 91, 27));
        txtMedicinesDosage->setFont(font5);
        txtMedicinesTimesTaken = new QLineEdit(tabMedicine);
        txtMedicinesTimesTaken->setObjectName("txtMedicinesTimesTaken");
        txtMedicinesTimesTaken->setGeometry(QRect(190, 150, 41, 27));
        txtMedicinesTimesTaken->setFont(font5);
        lblMedicinesTimesTaken = new QLabel(tabMedicine);
        lblMedicinesTimesTaken->setObjectName("lblMedicinesTimesTaken");
        lblMedicinesTimesTaken->setGeometry(QRect(20, 150, 111, 24));
        lblMedicinesTimesTaken->setFont(font4);
        lblMediconesComment = new QLabel(tabMedicine);
        lblMediconesComment->setObjectName("lblMediconesComment");
        lblMediconesComment->setGeometry(QRect(20, 200, 81, 24));
        lblMediconesComment->setFont(font4);
        txtMedicinesComment = new QLineEdit(tabMedicine);
        txtMedicinesComment->setObjectName("txtMedicinesComment");
        txtMedicinesComment->setGeometry(QRect(190, 200, 291, 27));
        txtMedicinesComment->setFont(font5);
        lblMedicinesStartDate = new QLabel(tabMedicine);
        lblMedicinesStartDate->setObjectName("lblMedicinesStartDate");
        lblMedicinesStartDate->setGeometry(QRect(20, 20, 101, 23));
        lblMedicinesStartDate->setFont(font4);
        medicineStartDateEdit = new QDateEdit(tabMedicine);
        medicineStartDateEdit->setObjectName("medicineStartDateEdit");
        medicineStartDateEdit->setGeometry(QRect(190, 20, 151, 27));
        medicineStartDateEdit->setFont(font3);
        medicineStartDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        medicineStartDateEdit->setCalendarPopup(true);
        medicineEndDateEdit = new QDateEdit(tabMedicine);
        medicineEndDateEdit->setObjectName("medicineEndDateEdit");
        medicineEndDateEdit->setGeometry(QRect(190, 60, 151, 27));
        medicineEndDateEdit->setFont(font3);
        medicineEndDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        medicineEndDateEdit->setCalendarPopup(true);
        tabWidget->addTab(tabMedicine, QString());
        tabPathology = new QWidget();
        tabPathology->setObjectName("tabPathology");
        lblPathologyDate = new QLabel(tabPathology);
        lblPathologyDate->setObjectName("lblPathologyDate");
        lblPathologyDate->setGeometry(QRect(20, 20, 61, 23));
        lblPathologyDate->setFont(font4);
        lblPathologyCholesterol = new QLabel(tabPathology);
        lblPathologyCholesterol->setObjectName("lblPathologyCholesterol");
        lblPathologyCholesterol->setGeometry(QRect(20, 70, 101, 24));
        lblPathologyCholesterol->setFont(font4);
        txtPathologyCholesterol = new QLineEdit(tabPathology);
        txtPathologyCholesterol->setObjectName("txtPathologyCholesterol");
        txtPathologyCholesterol->setGeometry(QRect(210, 70, 61, 27));
        txtPathologyCholesterol->setFont(font5);
        lblPathologyHDL = new QLabel(tabPathology);
        lblPathologyHDL->setObjectName("lblPathologyHDL");
        lblPathologyHDL->setGeometry(QRect(20, 120, 41, 23));
        lblPathologyHDL->setFont(font4);
        txtPathologyHDL = new QLineEdit(tabPathology);
        txtPathologyHDL->setObjectName("txtPathologyHDL");
        txtPathologyHDL->setGeometry(QRect(210, 120, 81, 27));
        txtPathologyHDL->setFont(font5);
        lblPathologyTriglycerides = new QLabel(tabPathology);
        lblPathologyTriglycerides->setObjectName("lblPathologyTriglycerides");
        lblPathologyTriglycerides->setGeometry(QRect(20, 170, 131, 24));
        lblPathologyTriglycerides->setFont(font4);
        txtPathologyTriglycerides = new QLineEdit(tabPathology);
        txtPathologyTriglycerides->setObjectName("txtPathologyTriglycerides");
        txtPathologyTriglycerides->setGeometry(QRect(210, 170, 81, 27));
        txtPathologyTriglycerides->setFont(font5);
        lblPathologyGlucose = new QLabel(tabPathology);
        lblPathologyGlucose->setObjectName("lblPathologyGlucose");
        lblPathologyGlucose->setGeometry(QRect(420, 70, 131, 24));
        lblPathologyGlucose->setFont(font4);
        lblPathologyGlucose->setContextMenuPolicy(Qt::NoContextMenu);
        txtPathologyGlucose = new QLineEdit(tabPathology);
        txtPathologyGlucose->setObjectName("txtPathologyGlucose");
        txtPathologyGlucose->setGeometry(QRect(610, 70, 81, 27));
        txtPathologyGlucose->setFont(font5);
        txtPathologyGlucose->setContextMenuPolicy(Qt::NoContextMenu);
        pathologyDateEdit = new QDateEdit(tabPathology);
        pathologyDateEdit->setObjectName("pathologyDateEdit");
        pathologyDateEdit->setGeometry(QRect(210, 20, 151, 27));
        pathologyDateEdit->setFont(font3);
        pathologyDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        pathologyDateEdit->setCalendarPopup(true);
        lblPathologyHbA1c = new QLabel(tabPathology);
        lblPathologyHbA1c->setObjectName("lblPathologyHbA1c");
        lblPathologyHbA1c->setGeometry(QRect(420, 120, 131, 24));
        lblPathologyHbA1c->setFont(font4);
        lblPathologyHbA1c->setContextMenuPolicy(Qt::NoContextMenu);
        txtPathologyHbA1c = new QLineEdit(tabPathology);
        txtPathologyHbA1c->setObjectName("txtPathologyHbA1c");
        txtPathologyHbA1c->setGeometry(QRect(610, 120, 81, 27));
        txtPathologyHbA1c->setFont(font5);
        txtPathologyHbA1c->setContextMenuPolicy(Qt::NoContextMenu);
        lblPathologyOneHour = new QLabel(tabPathology);
        lblPathologyOneHour->setObjectName("lblPathologyOneHour");
        lblPathologyOneHour->setGeometry(QRect(420, 170, 131, 24));
        lblPathologyOneHour->setFont(font4);
        lblPathologyOneHour->setContextMenuPolicy(Qt::NoContextMenu);
        txtPathologyOneHour = new QLineEdit(tabPathology);
        txtPathologyOneHour->setObjectName("txtPathologyOneHour");
        txtPathologyOneHour->setGeometry(QRect(610, 170, 81, 27));
        txtPathologyOneHour->setFont(font5);
        txtPathologyOneHour->setContextMenuPolicy(Qt::NoContextMenu);
        lblPathologyTwoHour = new QLabel(tabPathology);
        lblPathologyTwoHour->setObjectName("lblPathologyTwoHour");
        lblPathologyTwoHour->setGeometry(QRect(420, 220, 131, 24));
        lblPathologyTwoHour->setFont(font4);
        lblPathologyTwoHour->setContextMenuPolicy(Qt::NoContextMenu);
        txtPathologyTwoHour = new QLineEdit(tabPathology);
        txtPathologyTwoHour->setObjectName("txtPathologyTwoHour");
        txtPathologyTwoHour->setGeometry(QRect(610, 220, 81, 27));
        txtPathologyTwoHour->setFont(font5);
        txtPathologyTwoHour->setContextMenuPolicy(Qt::NoContextMenu);
        tabWidget->addTab(tabPathology, QString());
        tabWeights = new QWidget();
        tabWeights->setObjectName("tabWeights");
        lblWeightsTime = new QLabel(tabWeights);
        lblWeightsTime->setObjectName("lblWeightsTime");
        lblWeightsTime->setGeometry(QRect(20, 60, 61, 23));
        lblWeightsTime->setFont(font4);
        cboWeightsTime = new QComboBox(tabWeights);
        cboWeightsTime->setObjectName("cboWeightsTime");
        cboWeightsTime->setGeometry(QRect(210, 60, 121, 27));
        cboWeightsTime->setFont(font4);
        lblWeightsWeight = new QLabel(tabWeights);
        lblWeightsWeight->setObjectName("lblWeightsWeight");
        lblWeightsWeight->setGeometry(QRect(20, 110, 81, 23));
        lblWeightsWeight->setFont(font4);
        txtWeightsWeight = new QLineEdit(tabWeights);
        txtWeightsWeight->setObjectName("txtWeightsWeight");
        txtWeightsWeight->setGeometry(QRect(210, 110, 61, 27));
        txtWeightsWeight->setFont(font5);
        lblWeightsDate = new QLabel(tabWeights);
        lblWeightsDate->setObjectName("lblWeightsDate");
        lblWeightsDate->setGeometry(QRect(20, 20, 61, 23));
        lblWeightsDate->setFont(font4);
        lblWeightsComment = new QLabel(tabWeights);
        lblWeightsComment->setObjectName("lblWeightsComment");
        lblWeightsComment->setGeometry(QRect(20, 160, 111, 23));
        lblWeightsComment->setFont(font4);
        txtWeightsComment = new QLineEdit(tabWeights);
        txtWeightsComment->setObjectName("txtWeightsComment");
        txtWeightsComment->setGeometry(QRect(210, 160, 311, 27));
        txtWeightsComment->setFont(font5);
        weightsDateEdit = new QDateEdit(tabWeights);
        weightsDateEdit->setObjectName("weightsDateEdit");
        weightsDateEdit->setGeometry(QRect(210, 20, 151, 27));
        weightsDateEdit->setFont(font3);
        weightsDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        weightsDateEdit->setCalendarPopup(true);
        btnWeightsTomorrow = new QPushButton(tabWeights);
        btnWeightsTomorrow->setObjectName("btnWeightsTomorrow");
        btnWeightsTomorrow->setGeometry(QRect(390, 20, 91, 27));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush63(QColor(195, 181, 102, 255));
        brush63.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush63);
        QBrush brush64(QColor(255, 243, 171, 255));
        brush64.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush64);
        QBrush brush65(QColor(225, 212, 136, 255));
        brush65.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush65);
        QBrush brush66(QColor(97, 90, 51, 255));
        brush66.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush66);
        QBrush brush67(QColor(130, 121, 68, 255));
        brush67.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush67);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush63);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush68(QColor(225, 218, 178, 255));
        brush68.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush68);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush69(QColor(0, 0, 0, 128));
        brush69.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette::Active, QPalette::PlaceholderText, brush69);
#endif
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush63);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush64);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush65);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush66);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush67);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush63);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush68);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        QBrush brush70(QColor(0, 0, 0, 128));
        brush70.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush70);
#endif
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush66);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush63);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush64);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush65);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush66);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush67);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush66);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush66);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush63);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush63);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush63);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        QBrush brush71(QColor(0, 0, 0, 128));
        brush71.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush71);
#endif
        btnWeightsTomorrow->setPalette(palette9);
        btnWeightsTomorrow->setFont(font5);
        tabWidget->addTab(tabWeights, QString());
        tabEyes = new QWidget();
        tabEyes->setObjectName("tabEyes");
        lblEyesDate = new QLabel(tabEyes);
        lblEyesDate->setObjectName("lblEyesDate");
        lblEyesDate->setGeometry(QRect(20, 20, 61, 23));
        lblEyesDate->setFont(font4);
        lblEyesReason = new QLabel(tabEyes);
        lblEyesReason->setObjectName("lblEyesReason");
        lblEyesReason->setGeometry(QRect(20, 70, 71, 23));
        lblEyesReason->setFont(font4);
        txtEyesReason = new QLineEdit(tabEyes);
        txtEyesReason->setObjectName("txtEyesReason");
        txtEyesReason->setGeometry(QRect(210, 70, 211, 27));
        txtEyesReason->setFont(font5);
        lblEyesComment = new QLabel(tabEyes);
        lblEyesComment->setObjectName("lblEyesComment");
        lblEyesComment->setGeometry(QRect(20, 120, 91, 23));
        lblEyesComment->setFont(font4);
        txtEyesComment = new QLineEdit(tabEyes);
        txtEyesComment->setObjectName("txtEyesComment");
        txtEyesComment->setGeometry(QRect(210, 120, 381, 27));
        txtEyesComment->setFont(font5);
        eyesDateEdit = new QDateEdit(tabEyes);
        eyesDateEdit->setObjectName("eyesDateEdit");
        eyesDateEdit->setGeometry(QRect(210, 20, 151, 27));
        eyesDateEdit->setFont(font3);
        eyesDateEdit->setButtonSymbols(QAbstractSpinBox::NoButtons);
        eyesDateEdit->setCalendarPopup(true);
        tabWidget->addTab(tabEyes, QString());
        tabsTest->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(tabsTest);
        statusbar->setObjectName("statusbar");
        statusbar->setFont(font3);
        tabsTest->setStatusBar(statusbar);
#if QT_CONFIG(shortcut)
        lblActivityDuration->setBuddy(txtActivityDuration);
        lblActivityDistance->setBuddy(txtActivityDistance);
#endif // QT_CONFIG(shortcut)
        QWidget::setTabOrder(tabWidget, cboActivityActivity);
        QWidget::setTabOrder(cboActivityActivity, cboActivityModel);
        QWidget::setTabOrder(cboActivityModel, txtActivityDistance);
        QWidget::setTabOrder(txtActivityDistance, txtActivityDuration);
        QWidget::setTabOrder(txtActivityDuration, txtActivityComment);
        QWidget::setTabOrder(txtActivityComment, txtAppointmentsType);
        QWidget::setTabOrder(txtAppointmentsType, txtAppointmentsName);
        QWidget::setTabOrder(txtAppointmentsName, txtAppointmentsComment);
        QWidget::setTabOrder(txtAppointmentsComment, txtExerciseSets);
        QWidget::setTabOrder(txtExerciseSets, txtExerciseReps);
        QWidget::setTabOrder(txtExerciseReps, txtExerciseWeight);
        QWidget::setTabOrder(txtExerciseWeight, txtExerciseDuration);
        QWidget::setTabOrder(txtExerciseDuration, txtExerciseComment);
        QWidget::setTabOrder(txtExerciseComment, txtIllnessName);
        QWidget::setTabOrder(txtIllnessName, txtIllnessComment);
        QWidget::setTabOrder(txtIllnessComment, txtInjuryName);
        QWidget::setTabOrder(txtInjuryName, txtInjuryComment);
        QWidget::setTabOrder(txtInjuryComment, cboMedicinesMedicine);
        QWidget::setTabOrder(cboMedicinesMedicine, txtMedicinesDosage);
        QWidget::setTabOrder(txtMedicinesDosage, cboMedicinesUnit);
        QWidget::setTabOrder(cboMedicinesUnit, txtMedicinesTimesTaken);
        QWidget::setTabOrder(txtMedicinesTimesTaken, txtMedicinesComment);
        QWidget::setTabOrder(txtMedicinesComment, txtPathologyCholesterol);
        QWidget::setTabOrder(txtPathologyCholesterol, txtPathologyHDL);
        QWidget::setTabOrder(txtPathologyHDL, txtPathologyTriglycerides);
        QWidget::setTabOrder(txtPathologyTriglycerides, txtPathologyGlucose);
        QWidget::setTabOrder(txtPathologyGlucose, cboWeightsTime);
        QWidget::setTabOrder(cboWeightsTime, txtWeightsWeight);
        QWidget::setTabOrder(txtWeightsWeight, txtWeightsComment);
        QWidget::setTabOrder(txtWeightsComment, txtEyesReason);
        QWidget::setTabOrder(txtEyesReason, txtEyesComment);
        QWidget::setTabOrder(txtEyesComment, activityDateEdit);
        QWidget::setTabOrder(activityDateEdit, txtActivityHeartRate);
        QWidget::setTabOrder(txtActivityHeartRate, txtActivityMaxHeartRate);
        QWidget::setTabOrder(txtActivityMaxHeartRate, cboActivityComments);
        QWidget::setTabOrder(cboActivityComments, appointmentsDateEdit);
        QWidget::setTabOrder(appointmentsDateEdit, exerciseDateEdit);
        QWidget::setTabOrder(exerciseDateEdit, cboExerciseExercise);
        QWidget::setTabOrder(cboExerciseExercise, txtExerciseHeartRate);
        QWidget::setTabOrder(txtExerciseHeartRate, txtExerciseMaxHeartRate);
        QWidget::setTabOrder(txtExerciseMaxHeartRate, illnessDateEdit);
        QWidget::setTabOrder(illnessDateEdit, injuryDateEdit);
        QWidget::setTabOrder(injuryDateEdit, medicineStartDateEdit);
        QWidget::setTabOrder(medicineStartDateEdit, medicineEndDateEdit);
        QWidget::setTabOrder(medicineEndDateEdit, pathologyDateEdit);
        QWidget::setTabOrder(pathologyDateEdit, weightsDateEdit);
        QWidget::setTabOrder(weightsDateEdit, eyesDateEdit);
        QWidget::setTabOrder(eyesDateEdit, btnView);
        QWidget::setTabOrder(btnView, btnReset);
        QWidget::setTabOrder(btnReset, btnUpdate);
        QWidget::setTabOrder(btnUpdate, btnExit);

        retranslateUi(tabsTest);
        QObject::connect(btnExit, &QPushButton::clicked, tabsTest, qOverload<>(&QMainWindow::close));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(tabsTest);
    } // setupUi

    void retranslateUi(QMainWindow *tabsTest)
    {
        tabsTest->setWindowTitle(QCoreApplication::translate("tabsTest", "Health Database System", nullptr));
        btnReset->setText(QCoreApplication::translate("tabsTest", "Reset", nullptr));
        btnView->setText(QCoreApplication::translate("tabsTest", "View", nullptr));
        btnExit->setText(QCoreApplication::translate("tabsTest", "Exit", nullptr));
        btnUpdate->setText(QCoreApplication::translate("tabsTest", "Add", nullptr));
        lblActivityDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblActivityActivity->setText(QCoreApplication::translate("tabsTest", "Activity", nullptr));
        lblActivityDuration->setText(QCoreApplication::translate("tabsTest", "Duration (h:mm:ss)", nullptr));
        lblActivityComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        lblActivityDistance->setText(QCoreApplication::translate("tabsTest", "Distance (kk.k)", nullptr));
        lblActivityHeartRate->setText(QCoreApplication::translate("tabsTest", "Heart rate", nullptr));
        lblActivityMaxHeartRate->setText(QCoreApplication::translate("tabsTest", "Max heart rate", nullptr));
        btnActivityLaps->setText(QCoreApplication::translate("tabsTest", "Laps", nullptr));
        btnActivityCalculate->setText(QCoreApplication::translate("tabsTest", "Calculate", nullptr));
        lblActivityDistance2->setText(QCoreApplication::translate("tabsTest", "Distance (kk.kk)", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabActivity), QCoreApplication::translate("tabsTest", "Activity", nullptr));
        lblAppointmentsDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblAppointmentsType->setText(QCoreApplication::translate("tabsTest", "Type", nullptr));
        lblAppointmentsName->setText(QCoreApplication::translate("tabsTest", "Name", nullptr));
        lblAppointmentsComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabAppointments), QCoreApplication::translate("tabsTest", "Appointments", nullptr));
        lblExerciseDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblExerciseExercise->setText(QCoreApplication::translate("tabsTest", "Exercise", nullptr));
        lblExerciseDuration->setText(QCoreApplication::translate("tabsTest", "Duration (mm:ss)", nullptr));
        lblExerciseComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        lblExerciseReps->setText(QCoreApplication::translate("tabsTest", "Reps", nullptr));
        lblExerciseHeartRate->setText(QCoreApplication::translate("tabsTest", "Heart rate", nullptr));
        lblExerciseMaxHeartRate->setText(QCoreApplication::translate("tabsTest", "Max heart rate", nullptr));
        lblExerciseSets->setText(QCoreApplication::translate("tabsTest", "Sets", nullptr));
        lblExerciseWeight->setText(QCoreApplication::translate("tabsTest", "Weight", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabExercise), QCoreApplication::translate("tabsTest", "Exercise", nullptr));
        lblIllnessName->setText(QCoreApplication::translate("tabsTest", "Name", nullptr));
        lblIllnessComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        lblIllnessDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabIllness), QCoreApplication::translate("tabsTest", "Illness", nullptr));
        lblInjuryDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblInjuryName->setText(QCoreApplication::translate("tabsTest", "Name", nullptr));
        lblInjuryComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabInjury), QCoreApplication::translate("tabsTest", "Injury", nullptr));
        lblMouthDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblMouthTime->setText(QCoreApplication::translate("tabsTest", "Time", nullptr));
        lblMouthTypeOfProblem->setText(QCoreApplication::translate("tabsTest", "Type", nullptr));
        lblMouthTooth1->setText(QCoreApplication::translate("tabsTest", "Tooth1", nullptr));
        lblMouthTooth2->setText(QCoreApplication::translate("tabsTest", "Tooth2", nullptr));
        lblMouthComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabMouthProblems), QCoreApplication::translate("tabsTest", "Mouth", nullptr));
        lblMedicinesEndDate->setText(QCoreApplication::translate("tabsTest", "End date", nullptr));
        lblMedicinesMedicine->setText(QCoreApplication::translate("tabsTest", "Medicine", nullptr));
        lblMedicinesTimesTaken->setText(QCoreApplication::translate("tabsTest", "Times taken", nullptr));
        lblMediconesComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        lblMedicinesStartDate->setText(QCoreApplication::translate("tabsTest", "Start date", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabMedicine), QCoreApplication::translate("tabsTest", "Medicines", nullptr));
        lblPathologyDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblPathologyCholesterol->setText(QCoreApplication::translate("tabsTest", "Cholesterol", nullptr));
        lblPathologyHDL->setText(QCoreApplication::translate("tabsTest", "HDL", nullptr));
        lblPathologyTriglycerides->setText(QCoreApplication::translate("tabsTest", "Triglycerides", nullptr));
        lblPathologyGlucose->setText(QCoreApplication::translate("tabsTest", "Glucose", nullptr));
        lblPathologyHbA1c->setText(QCoreApplication::translate("tabsTest", "HbA1c", nullptr));
        lblPathologyOneHour->setText(QCoreApplication::translate("tabsTest", "one hour", nullptr));
        txtPathologyOneHour->setText(QString());
        lblPathologyTwoHour->setText(QCoreApplication::translate("tabsTest", "two hour", nullptr));
        txtPathologyTwoHour->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tabPathology), QCoreApplication::translate("tabsTest", "Pathology", nullptr));
        lblWeightsTime->setText(QCoreApplication::translate("tabsTest", "Time", nullptr));
        lblWeightsWeight->setText(QCoreApplication::translate("tabsTest", "Weight", nullptr));
        lblWeightsDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblWeightsComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        btnWeightsTomorrow->setText(QCoreApplication::translate("tabsTest", "Tomorrow", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabWeights), QCoreApplication::translate("tabsTest", "Weight", nullptr));
        lblEyesDate->setText(QCoreApplication::translate("tabsTest", "Date", nullptr));
        lblEyesReason->setText(QCoreApplication::translate("tabsTest", "Reason", nullptr));
        lblEyesComment->setText(QCoreApplication::translate("tabsTest", "Comment", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tabEyes), QCoreApplication::translate("tabsTest", "Eyes", nullptr));
    } // retranslateUi

};

namespace Ui {
    class tabsTest: public Ui_tabsTest {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TABSTEST_H
